### ISSUE TITLE
Just say Hi from SeaweedFS

### ISSUE THREAD

**Issue by chrislusf** [geohot/minikeyvalue#22]
Hi, George, 

You are one of the guys that I respect. I was watching the youtube video https://www.youtube.com/watch?v=iwcYp-XT7UI where Lex Fridman interviewed you, and you mentioned SeaweedFS for 0.5 seconds. :) 

I work on SeaweedFS. And I wanted to learn your approach to file storage. In another coding session, you mentioned SeaweedFS has some bugs. If you still remember the exact bugs, please let me know.

Thanks and keep up the nice work!

Chris

**Comment by geohot** [comment]
Hi! Yea, we checked out using SeaweedFS, iirc there was a bug with range requests that you fixed quickly.

The main reason we rolled our own was to have the on disk storage format be very simple in case of recovery from catastrophic failure. It's fine for us to just use the filesystem, since files are all bigger than 1MB.

Keep up the good work as well!

George
